name: Fetch PIA Servers

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: ["master"]
    paths: [".github/workflows/fetch-servers.yml", "src/**", "pom.xml"]

jobs:
  docker:
    strategy:
      matrix:
        arch: [ "self-hosted" ]
        git-version: [ "2.44.0" ]
        java-version: [ "17" ]
        maven-version: [ "3.8.5" ]
    runs-on: ${{ matrix.arch }}

    # Steps to run
    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Setup Java and Maven
      - name: Set up JDK and Maven
        uses: s4u/setup-maven-action@v1.17.0
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "zulu"
          maven-version: ${{ matrix.maven-version }}

      # Build the app and run it
      - name: Build and Run
        run: mvn clean package -q -T4C && java -jar target/PIA-ServerList.jar

      - name: Commit Changes
        run: |
          git config --global user.email "github-ci@rainnny.club"
          git config --global user.name "Rainnny-CI"
          git add servers.json
          git add README.md
          git commit -m "Scheduled update"
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/Rainnny7/PIA-ServerList